// Typelizer digest 1f157baf029c8f3e703a761323725549
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/schedules */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/schedules', {}, options),
    method: 'get',
  }),

  /** POST /settings/schedules */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/settings/schedules', {}, options),
    method: 'post',
  }),
}
