# frozen_string_literal: true

require "rails_helper"
require "inertia_rails/rspec"

RSpec.describe "Consumer Accounts", type: :request do
  fixtures :users

  def setup_consumer(name: "Lucía", email: "consumer-accounts@gmail.com")
    company = Company.create!(name: "GoGrow", address: "18 de Julio 1006")
    user = User.create!(email:, name:, password: "password123456")
    consumer = Consumer.create!(user:, company:, address: "Ellauri 1234")
    [ user, consumer, company ]
  end

  def setup_provider(name: "Rotisería del Prado", email: "rotiseria@gmail.com")
    user = User.create!(email:, name:, password: "password123456")
    Provider.create!(user:)
  end

  def create_order(consumer:, provider:, price: 350, amount: 1, status: :confirmed, date: Date.current.beginning_of_week(:monday))
    menu = Menu.create!(provider:, name: "Menú #{SecureRandom.hex(3)}", description: "Descripción", price:)
    schedule = Schedule.create!(menu:, date:, amount: 30)
    Order.create!(
      consumer:,
      schedule:,
      amount:,
      price: price * amount,
      discounted_price: (price * amount) * 0.5,
      address: consumer.address,
      status:
    )
  end

  describe "GET /accounts" do
    it "redirects unauthenticated users to sign in" do
      get accounts_path

      expect(response).to redirect_to(sign_in_path)
    end

    it "redirects users that do not have the consumer role" do
      provider = setup_provider
      sign_in(provider.user, role: :provider)

      get accounts_path

      expect(response).to have_http_status(:redirect)
    end

    it "renders the monthly debt and spending generated by consumer orders" do
      user, consumer, = setup_consumer
      provider = setup_provider
      sign_in(user, role: :consumer)

      # 2 confirmed orders in current month
      create_order(consumer:, provider:, price: 300, amount: 1, status: :confirmed)
      create_order(consumer:, provider:, price: 400, amount: 2, status: :confirmed)
      # 1 cancelled order that should not count towards debt
      create_order(consumer:, provider:, price: 500, amount: 1, status: :cancelled)

      get accounts_path

      expect(response).to have_http_status(:ok)
      expect(inertia).to render_component("consumer/accounts/index")
      expect(inertia).to have_props { |props|
        p = props.deep_symbolize_keys
        p[:current_month_spending].to_d == 1100.to_d &&
          p[:total_debt].to_d == 1100.to_d &&
          p[:history] == false &&
          p[:accounts].one? &&
          p[:accounts].first[:amount].to_d == 1100.to_d &&
          p[:accounts].first[:orders_amount_sum] == 3 &&
          p[:accounts].first[:orders_price_sum].to_d == 1100.to_d
      }
    end

    it "separates monthly debt by provider and lists providers without debt" do
      user, consumer, = setup_consumer
      provider1 = setup_provider(name: "Proveedor Pastas", email: "pastas@gmail.com")
      provider2 = setup_provider(name: "Proveedor Ensaladas", email: "ensaladas@gmail.com")
      provider_sin_deuda = setup_provider(name: "Proveedor Postres", email: "postres@gmail.com")

      sign_in(user, role: :consumer)

      # Orders with provider 1 ($350 * 2 = $700, 2 viandas)
      create_order(consumer:, provider: provider1, price: 350, amount: 2, status: :confirmed)

      # Orders with provider 2 ($250 * 1 = $250, 1 vianda)
      create_order(consumer:, provider: provider2, price: 250, amount: 1, status: :confirmed)

      get accounts_path

      expect(response).to have_http_status(:ok)
      expect(inertia).to render_component("consumer/accounts/index")
      expect(inertia).to have_props { |props|
        p = props.deep_symbolize_keys
        provider1_account = p[:accounts].find { |a| a[:provider_id] == provider1.id }
        provider2_account = p[:accounts].find { |a| a[:provider_id] == provider2.id }

        p[:current_month_spending].to_d == 950.to_d &&
          p[:total_debt].to_d == 950.to_d &&
          provider1_account[:amount].to_d == 700.to_d &&
          provider1_account[:orders_amount_sum] == 2 &&
          provider1_account[:orders_price_sum].to_d == 700.to_d &&
          provider2_account[:amount].to_d == 250.to_d &&
          provider2_account[:orders_amount_sum] == 1 &&
          provider2_account[:orders_price_sum].to_d == 250.to_d &&
          p[:providers].map { |pr| pr[:id] }.include?(provider_sin_deuda.id)
      }
    end

    it "includes pending debt from previous months in total_debt while current_month_spending reflects only the current month" do
      user, consumer, = setup_consumer
      provider = setup_provider
      sign_in(user, role: :consumer)

      # Current month order
      create_order(consumer:, provider:, price: 400, amount: 1, status: :confirmed)

      # Pending debt from previous month
      past_account = Account.create!(
        owner: consumer,
        provider: provider,
        month: 1.month.ago.beginning_of_month,
        amount: 600
      )

      get accounts_path

      expect(response).to have_http_status(:ok)
      expect(inertia).to have_props { |props|
        p = props.deep_symbolize_keys
        p[:current_month_spending].to_d == 400.to_d &&
          p[:total_debt].to_d == 1000.to_d &&
          p[:accounts].map { |a| a[:id] }.include?(past_account.id)
      }
    end

    it "isolates accounts between different consumers" do
      user1, consumer1, = setup_consumer(name: "Consumidor Uno", email: "c1@gmail.com")
      user2, consumer2, = setup_consumer(name: "Consumidor Dos", email: "c2@gmail.com")
      provider = setup_provider

      create_order(consumer: consumer1, provider:, price: 500, amount: 1, status: :confirmed)
      create_order(consumer: consumer2, provider:, price: 800, amount: 1, status: :confirmed)

      sign_in(user1, role: :consumer)
      get accounts_path

      expect(response).to have_http_status(:ok)
      expect(inertia).to have_props { |props|
        p = props.deep_symbolize_keys
        p[:current_month_spending].to_d == 500.to_d &&
          p[:total_debt].to_d == 500.to_d &&
          p[:accounts].one?
      }
    end
  end

  describe "GET /accounts/:id" do
    it "returns JSON with order details and amount for the specified account" do
      user, consumer, = setup_consumer
      provider = setup_provider
      sign_in(user, role: :consumer)

      order1 = create_order(consumer:, provider:, price: 300, amount: 2, status: :confirmed)
      order2 = create_order(consumer:, provider:, price: 200, amount: 1, status: :confirmed)
      create_order(consumer:, provider:, price: 100, amount: 1, status: :cancelled)

      account = consumer.accounts.find_by!(provider:)

      get account_path(account), headers: { "ACCEPT" => "application/json" }

      expect(response).to have_http_status(:ok)
      json = JSON.parse(response.body)

      expect(json["amount"].to_d).to eq(800.to_d)
      expect(json["month"]).to be_present
      expect(json["orders"].size).to eq(2)
      expect(json["orders"].map { |o| o["id"] }).to contain_exactly(order1.id, order2.id)
      expect(json["orders"].first).to include("id", "amount", "price", "date", "menu_name")
    end

    it "returns not found when a consumer tries to view an account of another consumer" do
      user1, = setup_consumer(name: "Consumidor Uno", email: "c1-view@gmail.com")
      _user2, consumer2, = setup_consumer(name: "Consumidor Dos", email: "c2-view@gmail.com")
      provider = setup_provider

      other_account = Account.create!(
        owner: consumer2,
        provider: provider,
        month: Date.current,
        amount: 500
      )

      sign_in(user1, role: :consumer)

      get account_path(other_account), headers: { "ACCEPT" => "application/json" }

      expect(response).to have_http_status(:not_found)
    end
  end
end
