# En este archivo se registran todas las configuraciones de notificaciones y
# eventos que las generan en el sistema. Se recarga automáticamente en la aplicación
# cuando hay cambios.
#
# Ver más documentación en docs/notificaciones.rb

# Para definir una configuración, hay que agregar una clave única en esta lista
# e indicar para qué roles se puede configurar, y si es administrable por el
# usuario. Si se agrega o cambia una configuración hay que correr el comando:
#   bin/rails notifications:sync
configurations:
  order_updates:
    roles: [consumer]
    configurable: true
  debt_alerts:
    roles: [consumer]
    configurable: true

# En esta lista se definen los eventos que generan notificaciones. Para agregar
# uno, hay que especificar una de las claves de configuración de arriba en el
# atributo configuration, especificar un único rol de los que están disponibles
# para la configuración en role e indicar si requiere acción.
events:
  order_confirmation:
    configuration: order_updates
    role: consumer
    requires_action: false

  order_rejection:
    configuration: order_updates
    role: consumer
    requires_action: false

  order_withdrawal:
    configuration: order_updates
    role: consumer
    requires_action: false

  debt_threshold_exceeded:
    configuration: debt_alerts
    role: consumer
    requires_action: true
