// Typelizer digest da4ee9c1e81915be56b2cac6a4db2ede
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /dashboard(/:role) */
  index: (
    params: { role?: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard(/:role)', params, options),
    method: 'get',
  }),
}
