// Typelizer digest 7b2b72a8c9162b67d8ee8aae412c5325
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /menus */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/menus', {}, options),
    method: 'get',
  }),

  /** POST /menus */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/menus', {}, options),
    method: 'post',
  }),

  /** GET /menus/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/menus/new', {}, options),
    method: 'get',
  }),

  /** GET /menus/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/menus/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /menus/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/menus/:id', params, options),
    method: 'get',
  }),

  /** PATCH /menus/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/menus/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /menus/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/menus/:id', params, options),
    method: 'delete',
  }),
}
