// Typelizer digest 553ef1f6834266985d601bd89856c75a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /notifications/:id/close */
  close: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/notifications/:id/close', params, options),
    method: 'patch',
  }),
}
