// Typelizer digest 877bac02b019aa31598e8aa9eea9c856
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /auth/google_oauth2/callback */
  googleOauth2: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/auth/google_oauth2/callback', {}, options),
    method: 'get',
  }),

  /** GET /auth/failure */
  failure: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/auth/failure', {}, options),
    method: 'get',
  }),
}
