// Typelizer digest 5db486a16901bbafe287a71d0313656a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'get',
  }),

  /** GET /orders/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/orders/:id', params, options),
    method: 'get',
  }),
}
