// Typelizer digest 235387d9ad6109a4e2750476832256de
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /schedules/update_by_date */
  updateByDate: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/schedules/update_by_date', {}, options),
    method: 'patch',
  }),

  /** PATCH /schedules/:id/availability */
  availability: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/schedules/:id/availability', params, options),
    method: 'patch',
  }),

  /** GET /schedules */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'get',
  }),

  /** POST /schedules */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'post',
  }),
}
