// Typelizer digest 4b1ac0293d837969aa30a1518becb396
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /schedules */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'get',
  }),

  /** POST /schedules */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'post',
  }),
}
