// Typelizer digest c7a57e5ddc46b62bb5413eda878c5535
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /schedules/:id/availability */
  availability: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/schedules/:id/availability', params, options),
    method: 'patch',
  }),

  /** GET /schedules */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'get',
  }),

  /** POST /schedules */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/schedules', {}, options),
    method: 'post',
  }),

  /** DELETE /schedules/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/schedules/:id', params, options),
    method: 'delete',
  }),
}
