// Typelizer digest c8753e6f5968f98a3023e54d74b74b3f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sign_in */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/sign_in', {}, options),
    method: 'get',
  }),

  /** POST /sign_in */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/sign_in', {}, options),
    method: 'post',
  }),

  /** GET /sessions/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/sessions/:id/edit', params, options),
    method: 'get',
  }),

  /** PATCH /sessions/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /sessions/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'delete',
  }),
}
