// Typelizer digest abcd0c32202aa6f504a289e739416cd9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sign_in(/:role) */
  new: (
    params: { role?: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/sign_in(/:role)', params, options),
    method: 'get',
  }),

  /** DELETE /sessions/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'delete',
  }),
}
