// Typelizer digest bcb898e76fb31e07afbcf35e3342a765
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /sign_in(/:role) */
  new: (
    params: { role?: string | number },
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/sign_in(/:role)', params, options),
    method: 'get',
  }),

  /** GET /sessions/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/sessions/:id/edit', params, options),
    method: 'get',
  }),

  /** PATCH /sessions/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /sessions/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/sessions/:id', params, options),
    method: 'delete',
  }),
}
