// Typelizer digest d4a490076827065afa58302cf9d8b9b1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/account */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/account', {}, options),
    method: 'get',
  }),
}
