// Typelizer digest 1bd4572a38d0db00db971f8904639983
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/collections */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/collections', {}, options),
    method: 'get',
  }),

  /** GET /provider/collections/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/collections/:id', params, options),
    method: 'get',
  }),
}
