// Typelizer digest a3fb6e3034bfb757c32daeb6a31a8cbb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/dashboard', {}, options),
    method: 'get',
  }),
}
