// Typelizer digest bd45230995adadc9f669ce8424651081
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /provider/collections/:collection_id/debt_reminders */
  create: (
    params: { collectionId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/provider/collections/:collection_id/debt_reminders', params, options),
    method: 'post',
  }),
}
