// Typelizer digest 4341c1a6837650cea644ec5a8b315c71
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/invoices/:id/file */
  file: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/invoices/:id/file', params, options),
    method: 'get',
  }),

  /** POST /provider/invoices */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/provider/invoices', {}, options),
    method: 'post',
  }),

  /** DELETE /provider/invoices/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/provider/invoices/:id', params, options),
    method: 'delete',
  }),
}
