// Typelizer digest a33130a2633ac3dba9237d9e9607d4b3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /provider/menus/publish */
  publish: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/provider/menus/publish', {}, options),
    method: 'post',
  }),

  /** POST /provider/menus */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/provider/menus', {}, options),
    method: 'post',
  }),

  /** GET /provider/menus/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/menus/new', {}, options),
    method: 'get',
  }),

  /** GET /provider/menus/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/menus/:id/edit', params, options),
    method: 'get',
  }),

  /** PATCH /provider/menus/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/menus/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /provider/menus/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/provider/menus/:id', params, options),
    method: 'delete',
  }),
}
