// Typelizer digest a2482c5aac0f8d68b3e1c50a3d76515c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/operational_settings */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/operational_settings', {}, options),
    method: 'get',
  }),
}
