// Typelizer digest 9dde02d8b1450d40010c2ef04ca832a3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** PATCH /provider/orders/:id/confirm */
  confirm: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/orders/:id/confirm', params, options),
    method: 'patch',
  }),

  /** PATCH /provider/orders/:id/reject */
  reject: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/orders/:id/reject', params, options),
    method: 'patch',
  }),

  /** GET /provider/orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/orders', {}, options),
    method: 'get',
  }),

  /** GET /provider/orders/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/orders/:id', params, options),
    method: 'get',
  }),
}
