// Typelizer digest b455a82d00bb33e9aa6dc6746c7ed167
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/orders', {}, options),
    method: 'get',
  }),

  /** GET /provider/orders/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/orders/:id', params, options),
    method: 'get',
  }),
}
