// Typelizer digest b64fb1c5a87dfd1713b05fe8ecfcfc61
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** PATCH /provider/order_deadline */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/order_deadline', {}, options),
    method: 'patch',
  }),
}
