// Typelizer digest c50f04e86161accb48669f897213539c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/orders', {}, options),
    method: 'get',
  }),
}
