// Typelizer digest 968ef656730344721ce84019cd08e77b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/payments/:id/receipt */
  receipt: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/payments/:id/receipt', params, options),
    method: 'get',
  }),

  /** GET /provider/payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/payments', {}, options),
    method: 'get',
  }),

  /** PATCH /provider/payments/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/payments/:id', params, options),
    method: 'patch',
  }),
}
