// Typelizer digest 27cadc089c840b1cae7d281eee9b4ffe
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/payments/:id/receipt */
  receipt: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/payments/:id/receipt', params, options),
    method: 'get',
  }),

  /** PATCH /provider/payments/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/payments/:id', params, options),
    method: 'patch',
  }),
}
