// Typelizer digest 47ba239f33c5d26db33449509fde2326
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /provider/payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/provider/payments', {}, options),
    method: 'get',
  }),

  /** PATCH /provider/payments/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/provider/payments/:id', params, options),
    method: 'patch',
  }),
}
