// Typelizer digest 83a576746e408c61e0fc876a1cfddc5a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/benefit_configurations */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/benefit_configurations', {}, options),
    method: 'get',
  }),

  /** POST /admin/benefit_configurations */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/admin/benefit_configurations', {}, options),
    method: 'post',
  }),
}
