// Typelizer digest 77d93721906a6c6a9c3169a1a2374588
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/consumers */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/consumers', {}, options),
    method: 'get',
  }),

  /** GET /admin/consumers/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/consumers/:id', params, options),
    method: 'get',
  }),
}
