// Typelizer digest 453bc96def1f839efb1ffc66ab452453
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/dashboard', {}, options),
    method: 'get',
  }),
}
