// Typelizer digest 42b1e61c051d7326d9cfedb0878abe90
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** PATCH /admin/debt_alert */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/admin/debt_alert', {}, options),
    method: 'patch',
  }),
}
