// Typelizer digest 5fe8bfb6cab02ded3b9c32331c6fb882
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/invoices/:id/file */
  file: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/invoices/:id/file', params, options),
    method: 'get',
  }),

  /** GET /admin/invoices */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/invoices', {}, options),
    method: 'get',
  }),
}
