// Typelizer digest 9f6fa1e8f4753f6dcf7075b64a502ca5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/invoices/:id/file */
  file: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/invoices/:id/file', params, options),
    method: 'get',
  }),
}
