// Typelizer digest d2126df39ba94faeb3aec591a0809138
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/payments', {}, options),
    method: 'get',
  }),

  /** GET /admin/payments/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/payments/:id', params, options),
    method: 'get',
  }),
}
