// Typelizer digest fbe306a7111c6213211c410de6acead5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /admin/payments/:id/receipt */
  receipt: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/payments/:id/receipt', params, options),
    method: 'get',
  }),

  /** GET /admin/payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/payments', {}, options),
    method: 'get',
  }),

  /** POST /admin/payments */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/admin/payments', {}, options),
    method: 'post',
  }),

  /** GET /admin/payments/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/admin/payments/:id', params, options),
    method: 'get',
  }),

  /** DELETE /admin/payments/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/admin/payments/:id', params, options),
    method: 'delete',
  }),
}
