// Typelizer digest dc7ccc43351da7da23e5f7629eb48dca
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /admin/special_subsidies */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/admin/special_subsidies', {}, options),
    method: 'post',
  }),

  /** PATCH /admin/special_subsidies/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/admin/special_subsidies/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /admin/special_subsidies/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/admin/special_subsidies/:id', params, options),
    method: 'delete',
  }),
}
