// Typelizer digest 13bd1ecde849a4f6beeffd2599331f1b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Payment} from '@/types'

type Account = {
  id: number;
  month: string | null;
  amount: number | null;
  provider_id: number;
  payments: Array<Payment>;
}

export type { Account };
