// Typelizer digest 50217f82acafcdf81bf3066e3b9e656a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Payment} from '@/types'

type Account = {
  id: number;
  provider_id: number;
  amount?: number;
  current: boolean;
  month?: string;
  due_date: string;
  due_date_passed: boolean;
  orders_amount_sum: number;
  orders_price_sum: number;
  payments: Array<Payment>;
}

export type { Account };
