// Typelizer digest 84e6362fe9d9ee305b1937c872d83e4a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Payment} from '@/types'

type Account = {
  id: number;
  provider_id: number;
  amount: number | null;
  current: unknown;
  month: string | null;
  due_date: unknown;
  due_date_passed: unknown;
  orders_amount_sum: unknown;
  orders_price_sum: unknown;
  payments: Array<Payment>;
}

export type { Account };
