// Typelizer digest 45fe8aa987049b965f03846c865bfa26
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AdminConsumerOrder} from '@/types'

type AdminConsumerMonth = {
  key: string;
  year: number;
  amount: number;
  subsidy: number;
  label: string;
  status: 'pending' | 'submitted' | 'approved' | 'rejected' | null;
  providers: Array<{ name: string; amount: number; status: 'pending' | 'submitted' | 'approved' | 'rejected' }>;
  orders: Array<AdminConsumerOrder>;
}

export type { AdminConsumerMonth };
