// Typelizer digest 67afdd0b42d3c699a68d5c6490f00b5f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AdminConsumerRow} from '@/types'

type AdminConsumersIndex = {
  consumers: Array<AdminConsumerRow>;
}

export type { AdminConsumersIndex };
