// Typelizer digest ddd8513f1a024107c7ab854ca4929cd0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitConfiguration, SpecialSubsidy, Employee} from '@/types'

type AdminBenefitConfigurationsIndex = {
  benefit_configurations: Array<BenefitConfiguration>;
  pending_base_subsidies: Array<BenefitConfiguration>;
  base_subsidy: BenefitConfiguration;
  configurable_month: unknown;
  special_subsidies: Array<SpecialSubsidy>;
  employees: Array<Employee>;
}

export type { AdminBenefitConfigurationsIndex };
