// Typelizer digest 3a42f8fc59e400f558f256f5509bd64b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminConsumerOrder = {
  id: unknown;
  amount: unknown;
  date: unknown;
  provider_name: unknown;
  subsidy: unknown;
  charged: unknown;
}

export type { AdminConsumerOrder };
