// Typelizer digest 9ecc09ae518954c69ccf4a92a001ba17
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminInvoice = {
  id: unknown;
  status: unknown;
  period: unknown;
  issued_on: unknown;
  provider_name: unknown;
  total_amount: unknown;
  period_amount: unknown;
  file_name: unknown;
  file_size: unknown;
}

export type { AdminInvoice };
