// Typelizer digest 9109e444a9a82b1199bc2945d8b3e306
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Provider} from '@/types'

type AdminPaymentsIndex = {
  accounts: unknown;
  history: unknown;
  total_debt: unknown;
  current_month: unknown;
  providers: Array<Provider>;
}

export type { AdminPaymentsIndex };
