// Typelizer digest 508086d1f7fd6e018ee60ebe3468eb1c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminDashboardIndex = {
  today: string;
  payment_month: string;
}

export type { AdminDashboardIndex };
