// Typelizer digest dda1f513c644a93afffa4be6419100d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminDashboardIndex = {
  today: unknown;
  payment_month: unknown;
}

export type { AdminDashboardIndex };
