// Typelizer digest 20fb17586f27666e4b39794a57f94aaa
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Consumer, BenefitSummary, AdminConsumerMonth} from '@/types'

type AdminConsumersShow = {
  consumer: Consumer;
  summary: { amount: number; status: 'pending' | 'submitted' | 'approved' | 'rejected' | null; meals_used: number; meals_limit: number; providers: Array<{ name: string; meals: number }> };
  benefit_summary: BenefitSummary | null;
  months: Array<AdminConsumerMonth>;
}

export type { AdminConsumersShow };
