// Typelizer digest 19dbbad1bb222ddefb1058af024c3949
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitConfiguration, SpecialSubsidy, Employee} from '@/types'

type AdminBenefitConfigurationsIndex = {
  benefit_configurations: Array<BenefitConfiguration>;
  pending_base_subsidy: BenefitConfiguration | null;
  base_subsidy: BenefitConfiguration | null;
  special_subsidies: Array<SpecialSubsidy>;
  employees: Array<Employee>;
}

export type { AdminBenefitConfigurationsIndex };
