// Typelizer digest 6ca73ce9c47736f5bcd068ff4be68d76
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {InvoiceStatus} from '@/types'

type AdminInvoice = {
  id: number;
  status: InvoiceStatus;
  period: string;
  issued_on: string;
  provider_name: string;
  total_amount: number;
  period_amount?: number;
  file_name: string;
  file_size: string;
}

export type { AdminInvoice };
