// Typelizer digest 86cbaa123d5f0312e4ef81ef8d71570c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminConsumerOrder = {
  id: number;
  amount: number | null;
  date: string;
  provider_name?: string;
  subsidy: number;
  charged: number;
}

export type { AdminConsumerOrder };
