// Typelizer digest 10c2cbe884050a611ae3438bb8febd53
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminConsumerRow = {
  id: number;
  name: string;
  email: string;
  amount: number;
  status: 'pending' | 'submitted' | 'approved' | 'rejected' | null;
}

export type { AdminConsumerRow };
