// Typelizer digest 41b3cae1f9830241f3db8f83712f60ec
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type AdminConsumerRow = {
  id: unknown;
  name: unknown;
  email: unknown;
  amount: unknown;
  status: unknown;
}

export type { AdminConsumerRow };
