// Typelizer digest 8f6329e66b90a760138ea4281b96b09b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Consumer, Order, Benefit, Account, Payment} from '@/types'

type AdminConsumersShow = {
  consumer: Consumer;
  orders: Array<Order>;
  benefits: Array<Benefit>;
  debts: Array<Account>;
  payments: Array<Payment>;
}

export type { AdminConsumersShow };
