// Typelizer digest e77ae3b267f4edd225a3c01e122a7576
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AdminInvoice} from '@/types'

type AdminInvoicesIndex = {
  invoices: Array<AdminInvoice>;
}

export type { AdminInvoicesIndex };
