// Typelizer digest 006d0efa7efa83e497c44e593d2d9452
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitConfiguration} from '@/types'

type AdminBenefitConfigurationsIndex = {
  benefit_configurations: Array<BenefitConfiguration>;
  current_benefit_configuration: BenefitConfiguration | null;
}

export type { AdminBenefitConfigurationsIndex };
