// Typelizer digest 13aba6947a30ac8eb5f86bbf21b379bb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Consumer, BenefitSummary, AdminConsumerMonth} from '@/types'

type AdminConsumersShow = {
  consumer: Consumer;
  summary: unknown;
  benefit_summary: BenefitSummary;
  months: Array<AdminConsumerMonth>;
}

export type { AdminConsumersShow };
