// Typelizer digest 7f2bea791b32766098a7c4dafdda462b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {AdminConsumerOrder} from '@/types'

type AdminConsumerMonth = {
  key: unknown;
  year: unknown;
  amount: unknown;
  subsidy: unknown;
  label: unknown;
  status: unknown;
  providers: unknown;
  orders: Array<AdminConsumerOrder>;
}

export type { AdminConsumerMonth };
