// Typelizer digest 1dae6c72539f08abad58125f6f0bed06
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Account, Provider} from '@/types'

type AdminPaymentsIndex = {
  accounts: Array<Account>;
  history: Array<Account>;
  total_debt: number;
  current_month: { amount: number; meals: number; limit: number | null };
  providers: Array<Provider>;
}

export type { AdminPaymentsIndex };
