// Typelizer digest d19e7d460ca7a5db5e433e3967e4f7b4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Consumer} from '@/types'

type AdminConsumersIndex = {
  query: string;
  consumers: Array<Consumer>;
}

export type { AdminConsumersIndex };
