// Typelizer digest 53db23aa753ba4a1cf408c69447cee87
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitRule} from '@/types'

type BenefitConfiguration = {
  id: number;
  subsidy_percentage: number;
  created_at: string;
  benefit_rules: Array<BenefitRule>;
  created_by_name: unknown;
}

export type { BenefitConfiguration };
