// Typelizer digest 3133b11b302aeb6a165d75955caf6479
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitSummary = {
  total: number;
  base: number;
  specials: Array<{ name: string; percentage: number }>;
}

export type { BenefitSummary };
