// Typelizer digest f59d704f724e6acf8ce305cc7e2eae74
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitConfiguration = {
  id: number;
  subsidy_percentage: number;
  monthly_voucher_limit: number;
  max_voucher_price: number;
  effective_from: string;
  created_at: string;
  created_by_name: string;
}

export type { BenefitConfiguration };
