// Typelizer digest 37955748d73fc61440d1bc1a23dc1733
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Benefit = {
  id: number;
  amount: number | null;
  description: string | null;
  percentage: number | null;
  due_date?: string;
}

export type { Benefit };
