// Typelizer digest 77ecd5c1d6797c1ca3ca91318cad329e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitRule} from '@/types'

type BenefitConfiguration = {
  id: number;
  subsidy_percentage: number;
  created_at: string;
  benefit_rules: Array<BenefitRule>;
  created_by_name: string;
}

export type { BenefitConfiguration };
