// Typelizer digest 44c0387a5bee0bb640103777384b95b4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitRule = {
  id: number;
  type: string | null;
  limit: number | null;
  max_price: number | null;
  deadline_date: string | null;
  deadline_days: number | null;
  min_years: number | null;
  created_at: string;
  effective_from?: string;
}

export type { BenefitRule };
