// Typelizer digest e821f585624d7461f3c8a84b0926f648
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitRule = {
  id: number;
  type: string | null;
  limit: number | null;
  max_price: number | null;
  deadline_date: string | null;
  deadline_days: number | null;
  effective_from: string | null;
  min_years: number | null;
  created_at: string;
}

export type { BenefitRule };
