// Typelizer digest e1ef51fefcf140b3be8ad15e62623e4f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitRule = {
  id: number;
  type: string | null;
  limit: number | null;
  max_price: number | null;
  deadline_date: string | null;
  deadline_days: number | null;
  min_years: number | null;
  created_at: string;
  effective_from: string | null;
}

export type { BenefitRule };
