// Typelizer digest 961858a65915e1b2bce91c1cbb7c953d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type BenefitSummary = {
  total: unknown;
  base: unknown;
  specials: unknown;
}

export type { BenefitSummary };
