// Typelizer digest 3ed4429d1b9a5132ecadaa364616ec68
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerSchedule, ConsumerProvider} from '@/types'

type ConsumerMenusIndex = {
  date: unknown;
  schedules: Array<ConsumerSchedule>;
  providers: Array<ConsumerProvider>;
}

export type { ConsumerMenusIndex };
