// Typelizer digest 98e9f9e95db983e4b939850acbc218f4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Schedule} from '@/types'

type ConsumerMenu = {
  id: number;
  name: string | null;
  description: string | null;
  price: string;
  provider_name?: string;
  schedules: Array<Schedule>;
}

export type { ConsumerMenu };
