// Typelizer digest effccb6aeeaef41e5c5b3fb8e09566bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerProvider} from '@/types'

type ConsumerMenuWithProvider = {
  id: unknown;
  name: unknown;
  description: unknown;
  price: unknown;
  provider: ConsumerProvider;
}

export type { ConsumerMenuWithProvider };
