// Typelizer digest 6b52499b0bdd8d38f55b645a1ff6c6a1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardConfirmation = {
  total: number;
  orders: orders: Array<{ id: number; date: string; address: string; delivery_method: string; provider_name: string; name: string; quantity: number; discounted_price: number }>;
}

export type { ConsumerDashboardConfirmation };
