// Typelizer digest 484e053b9e860d9c19a3a66446fc4bff
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardIndex = {
  week: { start_date: string; end_date: string; days: Array<{ date: string; weekday: string; day: number }> };
  schedules: Array<{ id: number; date: string; remaining: number; sold_out: boolean; orders_closed: boolean; menu: { id: number; name: string; description: string | null; price: number; option_groups: Array<{ id: number; name: string; options: string[]; limit: number }>; provider_name: string; home_delivery: boolean; reviews: Array<{ id: number; description: string | null; rating: number | null; created_at: string }> } }>;
  benefit: { limit: number; used: number; percentage: number; monthly_limit: number; monthly_used: number; monthly_remaining: number; specials: Array<{ id: number; name: string; percentage: number; remaining: number | null; due_date: string | null }> };
  addresses: Array<{ id: string; label: string; address: string }>;
}

export type { ConsumerDashboardIndex };
