// Typelizer digest 987d350162a0f33b0c3ef002e98b3c9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type ConsumerOrdersIndex = {
  upcoming_orders: Array<Order>;
  past_orders: Array<Order>;
}

export type { ConsumerOrdersIndex };
