// Typelizer digest 3078286c9356b0ce47d588b2d8c289fe
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order, Provider} from '@/types'

type ConsumerOrdersIndex = {
  upcoming_orders: Array<Order>;
  past_orders: Array<Order>;
  providers: Array<Provider>;
}

export type { ConsumerOrdersIndex };
