// Typelizer digest baf0462033fa2e845a3a5321f064bf2d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Consumer = {
  id: number;
  address: string | null;
  name: string;
  email: string;
  company_name: string;
}

export type { Consumer };
