// Typelizer digest ded1c913a7ee03ce974e959da78f0fc4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardIndex = {
  week: { start_date: string; end_date: string; days: Array<{ date: string; weekday: string; day: number }> };
  schedules: Array<{ id: number; date: string; remaining: number; sold_out: boolean; menu: { id: number; name: string; description: string | null; price: number; fillings: string[]; sauces: string[]; provider_name: string; home_delivery: boolean; reviews: Array<{ id: number; description: string | null; rating: number | null; created_at: string }> } }>;
  benefit: { limit: number; used: number; percentage: number; monthly_limit: number; monthly_used: number; monthly_remaining: number };
  addresses: Array<{ id: string; label: string; address: string }>;
}

export type { ConsumerDashboardIndex };
