// Typelizer digest be11b898c35c96660d0b782585cfec7e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardConfirmation = {
  total: number;
  orders: Array<{ id: number; date: string; address: string; delivery_method: string; provider_name: string; name: string; quantity: number; discounted_price: number }>;
}

export type { ConsumerDashboardConfirmation };
