// Typelizer digest 77cc60851b790bfdd43ca66c3dc79ffc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerProvider = {
  id: number;
  order_deadline: string | null;
  name: string;
}

export type { ConsumerProvider };
