// Typelizer digest 7a7fb092393f0b3b9dd6cc6ee9421da9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerProvider = {
  id: unknown;
  order_deadline: unknown;
  name: unknown;
}

export type { ConsumerProvider };
