// Typelizer digest 55a7e57f08fb4ec1aa198eee5dcd0eec
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type ConsumerOrdersShow = {
  order: Order;
}

export type { ConsumerOrdersShow };
