// Typelizer digest 66a36affe9e449d14749f4952bf15c52
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Consumer = {
  id: number;
  address: string | null;
  name: unknown;
  email: unknown;
  company_name: unknown;
}

export type { Consumer };
