// Typelizer digest a7229760b6733070a3a313f3e6b59118
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerMenuWithProvider} from '@/types'

type ConsumerSchedule = {
  id: number;
  date: string | null;
  amount: number | null;
  menu: ConsumerMenuWithProvider;
}

export type { ConsumerSchedule };
