// Typelizer digest 6e969670428446ac045ccc8965577eea
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardConfirmation = {
  total: unknown;
  orders: unknown;
}

export type { ConsumerDashboardConfirmation };
