// Typelizer digest 2d99c5bd9c7c94f7682996b5f2c2572d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type ConsumerOrdersShow = {
  order: Order;
  delivery_addresses: Array<{ id: string; label: string; address: string }>;
  max_quantity: number;
  option_groups: Array<{ id: number; name: string; options: string[]; limit: number }>;
  editing: boolean;
}

export type { ConsumerOrdersShow };
