// Typelizer digest b0ff8fbf5cdde779752b7b2deec7c14c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type ConsumerOrdersShow = {
  order: Order;
  delivery_addresses: unknown;
  max_quantity: unknown;
  editing: unknown;
  option_groups: unknown;
}

export type { ConsumerOrdersShow };
