// Typelizer digest 1c389f2bbb4880169c8e06b113095155
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type ConsumerPayment = {
  id: number;
  status: PaymentStatus;
  amount: number;
  date: string;
  employee_name: string;
  receipt_url: string | null;
}

export type { ConsumerPayment };
