// Typelizer digest eeb1f3851cc7e557adf9e838bdacfd52
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitSummary} from '@/types'

type ConsumerProfilesShow = {
  benefit: { percentage: number; monthly_limit: number; monthly_remaining: number; max_price: number | null; due_date: string | null } | null;
  benefit_summary: BenefitSummary | null;
}

export type { ConsumerProfilesShow };
