// Typelizer digest 18c69df4722f84c9a3ea2a46e0e99756
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerProvider} from '@/types'

type ConsumerMenuWithProvider = {
  id: number;
  name: string | null;
  description: string | null;
  price: number | null;
  provider: ConsumerProvider;
}

export type { ConsumerMenuWithProvider };
