// Typelizer digest b237e1df66ced53a3c3511546c6acdf5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerMenuWithProvider} from '@/types'

type ConsumerSchedule = {
  id: number;
  date: string;
  amount: number | null;
  available: boolean;
  menu: ConsumerMenuWithProvider;
}

export type { ConsumerSchedule };
