// Typelizer digest 9a8bfd6b05f1962100382313536b53aa
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerProfilesShow = {
  benefit: { percentage: number; monthly_limit: number; monthly_remaining: number; max_price: number | null; due_date: string | null } | null;
}

export type { ConsumerProfilesShow };
