// Typelizer digest 5004eda1359a26f3eae0b607ea9a8061
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerMenu} from '@/types'

type ConsumerMenusShow = {
  menu: ConsumerMenu;
}

export type { ConsumerMenusShow };
