// Typelizer digest bd97f6441ae3882ddd1dedc6b07bd816
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerMenu} from '@/types'

type ConsumerMenusIndex = {
  menus: Array<ConsumerMenu>;
}

export type { ConsumerMenusIndex };
