// Typelizer digest ed27f554442fab8112eeb7837a582b79
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ConsumerDashboardIndex = {
  week: { start_date: string; end_date: string; days: Array<{ date: string; weekday: string; day: number }> };
  schedules: Array<{ id: number; date: string; remaining: number; sold_out: boolean; menu: { id: number; name: string; description: string | null; price: number; fillings: string[]; sauces: string[]; provider_name: string; home_delivery: boolean; reviews: Array<{ id: number; description: string | null; rating: number | null; created_at: string }> } }>;
  benefit: { limit: number; used: number; percentage: number };
  addresses: Array<{ id: string; label: string; address: string }>;
  order_confirmation: { total: number; orders: Array<{ id: number; date: string; address: string; address_label: string; provider_name: string; name: string; quantity: number; discounted_price: number }> } | null;
}

export type { ConsumerDashboardIndex };
