// Typelizer digest fdc7a032f307e1c2ddfba9400aad5d38
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {BenefitSummary} from '@/types'

type ConsumerProfilesShow = {
  benefit: unknown;
  benefit_summary: BenefitSummary;
}

export type { ConsumerProfilesShow };
