// Typelizer digest e299440e754eef22851f564093b7b305
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerMenuWithProvider} from '@/types'

type ConsumerSchedule = {
  id: number;
  date: string;
  amount: number;
  available: unknown;
  menu: ConsumerMenuWithProvider;
}

export type { ConsumerSchedule };
