// Typelizer digest 988a339f4d6a92747bcf51f21b6c0095
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ConsumerSchedule, ConsumerProvider} from '@/types'

type ConsumerMenusIndex = {
  date: string;
  schedules: Array<ConsumerSchedule>;
  providers: Array<ConsumerProvider>;
}

export type { ConsumerMenusIndex };
