// Typelizer digest 0dffc34fe39d6f9e150d383e8841ebf4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Consumer = {
  id: number;
  name: string | null;
  description: string | null;
  price: number | null;
  created_at: string;
  updated_at: string;
}

export type { Consumer };
