// Typelizer digest be6dca73be3ebc63aa5f87f008be1e31
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DashboardIndex = {
  role?: string;
}

export type { DashboardIndex };
