// Typelizer digest c1cbb215f3e29dcd7f3b8245dad1a10f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type DashboardIndex = {
  role: unknown;
}

export type { DashboardIndex };
