// Typelizer digest 5a22fe2ec8cfbc8ad7147f1902509ee1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Employee = {
  id: unknown;
  name: unknown;
  short_name: unknown;
}

export type { Employee };
