// Typelizer digest 8b29e94747b22101504cd3c34babc06e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Employee = {
  id: number;
  name: string;
  short_name: string;
}

export type { Employee };
