// Typelizer digest 816b8ab38ebec0e9a20d0888b7c47aac
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type InvoiceStatus = 'pending' | 'approved' | 'rejected';
export type OrderDeliveryMethod = 'office' | 'home';
export type OrderRejectionReason = 'out_of_stock' | 'duplicate_order' | 'customer_request' | 'order_error' | 'other';
export type OrderStatus = 'pending' | 'confirmed' | 'cancelled' | 'rejected';
export type PaymentStatus = 'pending' | 'submitted' | 'approved' | 'rejected';
export type SessionRole = 'provider' | 'admin' | 'consumer';
