// Typelizer digest f3c3557a1154919fb0af9bf51b950b5a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type OrderStatus = 'pending' | 'confirmed' | 'delivered' | 'cancelled';
export type SessionRole = 'provider' | 'admin' | 'consumer';
