// Typelizer digest ccce2802cee9bd19378edb81a1f9707b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type OrderDeliveryMethod = 'office' | 'home';
export type OrderStatus = 'pending' | 'confirmed' | 'cancelled' | 'rejected';
export type PaymentStatus = 'pending' | 'paid';
export type SessionRole = 'provider' | 'admin' | 'consumer';
