// Typelizer digest e8751f8a29c5f7405a70172a4feb1d07
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type IdentityPasswordResetsEdit = {
  email: unknown;
  sid: unknown;
}

export type { IdentityPasswordResetsEdit };
