// Typelizer digest 9a9a232f23e999bb318ef258a99de021
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Menu = {
  id: number;
  name: string | null;
  description: string | null;
  price: number | null;
  created_at: string;
  updated_at: string;
  option_groups: unknown;
}

export type { Menu };
