// Typelizer digest a2cec444d0f3f7fa51c1010f0766266a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type MenuOptionGroup = {
  id: number;
  name: string;
  options: Array<string>;
  limit: number;
}

type Menu = {
  id: number;
  name: string | null;
  description: string | null;
  price: number | null;
  option_groups: Array<MenuOptionGroup>;
  created_at: string;
  updated_at: string;
}

export type { Menu, MenuOptionGroup };
