// Typelizer digest 11f81cad3d8a07fa9301c39d44c1732c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Notification = {
  id: number;
  title: string | null;
  description: string | null;
  requires_action: boolean;
}

export type { Notification };
