// Typelizer digest a93d76132e7d84100d6d5c5d5399c2bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus, OrderDeliveryMethod} from '@/types'

type Order = {
  id: number;
  status: OrderStatus;
  delivery_method: OrderDeliveryMethod;
  amount: number | null;
  notes: string | null;
  address: string | null;
  date?: string;
  menu_name?: string;
  provider_name?: string;
  price?: number;
  discounted_price?: number;
  subsidy?: number;
}

export type { Order };
