// Typelizer digest 7265f7480a2c3c6fa90dbce9e536361b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type OrdersShow = {
  order: Order;
}

export type { OrdersShow };
