// Typelizer digest 06f999965c9be08b5ed06d0453bfb702
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus, OrderDeliveryMethod} from '@/types'

type Order = {
  id: number;
  status: OrderStatus;
  delivery_method: OrderDeliveryMethod;
  amount: number | null;
  notes: string | null;
  address: string | null;
  date?: string;
  menu_name?: string;
  provider_name?: string;
  price?: number;
  discounted_price?: number;
  subsidy?: number;
  cancellable: boolean;
  cancellation_block_reason?: string;
  selected_options: Array<{ group_id: number; name: string; values: string[] }>;
  modifiable: boolean;
  modification_block_reason?: string;
}

export type { Order };
