// Typelizer digest 8000e0471705ec724a1907d1f52e9df5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Order} from '@/types'

type OrdersIndex = {
  upcoming_orders: Array<Order>;
  past_orders: Array<Order>;
}

export type { OrdersIndex };
