// Typelizer digest 5f74bb1e9bec4d9eca75ddd2a915df1e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus, OrderDeliveryMethod} from '@/types'

type Order = {
  id: number;
  status: OrderStatus;
  delivery_method: OrderDeliveryMethod;
  amount: number | null;
  notes: string | null;
  address: string | null;
  date?: string;
  menu_name?: string;
  provider_name?: string;
  price?: number;
  discounted_price?: number;
  subsidy?: number;
  cancellable: boolean;
  cancellation_block_reason?: string;
}

export type { Order };
