// Typelizer digest d0da5f1c4a8c23ec3d5df9ca9f81ec57
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type Payment = {
  id: number;
  status: PaymentStatus;
  created_at: string;
  rejection_reason: string | null;
  receipt_url?: string;
  receipt_filename?: string;
  receipt_content_type?: string;
}

export type { Payment };
