// Typelizer digest 0c307f38ac2734350a49a5d7e2076121
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Payment = {
  id: number;
  status: number;
  created_at: string;
}

export type { Payment };
