// Typelizer digest 2720dac9226d84ca4abd79abf641af1f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Payment = {
  id: number;
  status: number | null;
  created_at: string;
}

export type { Payment };
