// Typelizer digest 15deb9b584586725b9e8f5aea13926bb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SavedMenu} from '@/types'

type ProviderMenusNew = {
  saved_menus: Array<SavedMenu>;
  today: string;
  maximum_publish_date: string;
  default_date: string | null;
  published: Array<{ date: string; menu_id: number }>;
}

export type { ProviderMenusNew };
