// Typelizer digest 7324653dd6f2a4094182bef4e2914979
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus, OrderDeliveryMethod, OrderRejectionReason} from '@/types'

type ProviderOrderDetail = {
  id: number;
  status: OrderStatus;
  amount: number | null;
  notes: string | null;
  price: number;
  delivery_date: string | null;
  time: string;
  consumer_name: string;
  menu_name: string;
  address: string | null;
  date: string | null;
  delivery_method: OrderDeliveryMethod;
  consumer_company: string | null;
  consumer_email: string;
  menu_description: string | null;
  menu_option_groups: Array<{ id: number; name: string; options: string[]; limit: number }>;
  discounted_price: number | null;
  subsidy: number | null;
  schedule_amount: number | null;
  remaining_amount: number | null;
  rejection_reason: OrderRejectionReason | null;
  rejection_details: string | null;
}

export type { ProviderOrderDetail };
