// Typelizer digest 37361da62cd9a9868918937bbe9a72da
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus, OrderDeliveryMethod} from '@/types'

type ProviderOrder = {
  id: number;
  status: OrderStatus;
  amount: number | null;
  notes: string | null;
  delivery_method: OrderDeliveryMethod;
  price: number;
  date: string | null;
  time: string;
  consumer_name: string;
  consumer_company: string | null;
  menu_name: string;
  address: string | null;
}

export type { ProviderOrder };
