// Typelizer digest 08ef5b8ccb51065e63d4bdcb7175a8d6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOrder} from '@/types'

type ProviderOrdersIndex = {
  today: unknown;
  upcoming_orders: Array<ProviderOrder>;
  past_orders: Array<ProviderOrder>;
}

export type { ProviderOrdersIndex };
