// Typelizer digest 206965d9054b9d02c55beb915c480f8b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderDashboardProvider} from '@/types'

type ProviderDashboardIndex = {
  provider: ProviderDashboardProvider;
}

export type { ProviderDashboardIndex };
