// Typelizer digest 0dba9a66e8fd50d4f2e702b21c47bbe7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type ProviderCollectionPayment = {
  id: number;
  status: PaymentStatus;
  date: string;
}

export type { ProviderCollectionPayment };
