// Typelizer digest 825deae6e0fcbea49391416bc2a6115b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionAccount} from '@/types'

type ProviderCollectionGroup = {
  key: string;
  meals: number;
  awaiting_count: number;
  rejected_count: number;
  client_id: number;
  client_name: string;
  month: string;
  total: number;
  confirmed_total: number;
  employees_total: number;
  employees_status: 'pending' | 'submitted' | 'approved' | 'rejected' | null;
  company: ProviderCollectionAccount | null;
  employees: Array<ProviderCollectionAccount>;
}

export type { ProviderCollectionGroup };
