// Typelizer digest 0b97ac93688b9a481dd21c3d9fee5bbe
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Provider = {
  id: number;
  home_delivery: boolean;
  name: string;
}

export type { Provider };
