// Typelizer digest bb5e2866715fb1b1ab315401dd9224eb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderDashboardProvider} from '@/types'

type ProviderDashboardIndex = {
  today: string;
  today_orders_count: number;
  pending_orders_count: number;
  office_orders_count: number;
  home_orders_count: number;
  order_deadline?: string;
  month_orders_count: number;
  month_dishes_count: number;
  average_rating?: number;
  provider: ProviderDashboardProvider;
}

export type { ProviderDashboardIndex };
