// Typelizer digest abd3dbfe6cfac69a9436408d350377a1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderInvoice = {
  id: unknown;
  status: unknown;
  removable: unknown;
  total_amount: unknown;
  issued_on: unknown;
  file_name: unknown;
  file_size: unknown;
}

export type { ProviderInvoice };
