// Typelizer digest b664264708c8c2e0d4f751ae23526db1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOperationalSettingsProvider} from '@/types'

type ProviderOperationalSettingsShow = {
  provider: ProviderOperationalSettingsProvider;
  order_deadline_passed_today: boolean;
}

export type { ProviderOperationalSettingsShow };
