// Typelizer digest 118567a2e10e3f0b506f44c6ff60da2f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOrderDetail} from '@/types'

type ProviderOrdersShow = {
  order: ProviderOrderDetail;
}

export type { ProviderOrdersShow };
