// Typelizer digest f386aa42279d7a6a7b57d58a7167a922
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type ProviderPayment = {
  id: number;
  status: PaymentStatus;
  amount: number;
  date: string;
  employee_name: string;
  receipt_url: string | null;
  receipt_content_type: string | null;
}

export type { ProviderPayment };
