// Typelizer digest ed86ecd50db0d7d54d69c3c504406968
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionGroup} from '@/types'

type ProviderCollectionsIndex = {
  sales: { total: number; meals: number };
  outstanding: { total: number; meals: number };
  clients: Array<{ id: number; name: string }>;
  pending: Array<ProviderCollectionGroup>;
  history: Array<ProviderCollectionGroup>;
}

export type { ProviderCollectionsIndex };
