// Typelizer digest faf7a8ac2f5e59442bc47572a35a02bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOrder} from '@/types'

type ProviderOrdersIndex = {
  orders: Array<ProviderOrder>;
}

export type { ProviderOrdersIndex };
