// Typelizer digest 39fc04d93abd4d1244c0453628f14379
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderDashboardProvider = {
  order_deadline: unknown;
}

export type { ProviderDashboardProvider };
