// Typelizer digest 6d42ff4c58607c5810173982d21e1b63
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOperationalSettingsProvider} from '@/types'

type ProviderOperationalSettingsShow = {
  provider: ProviderOperationalSettingsProvider;
}

export type { ProviderOperationalSettingsShow };
