// Typelizer digest 7ae636004102f4a932837a3667916e8c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderCollectionPayment = {
  id: unknown;
  status: unknown;
  rejection_reason: unknown;
  date: unknown;
  receipt_url: unknown;
  receipt_filename: unknown;
  receipt_content_type: unknown;
}

export type { ProviderCollectionPayment };
