// Typelizer digest bcb5b16f817c1155a4325ee56136ac32
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Menu} from '@/types'

type ProviderMenusEdit = {
  menu: Menu;
  saved_menu_id: number;
  schedule_date: string | null;
  today: string;
  maximum_publish_date: string;
  agenda: { mode: 'none' | 'single' | 'weekly' | 'range'; weekdays: number[]; date: string | null; starts_on: string | null; ends_on: string | null; amount: number | null };
  scheduled_days: Array<{ date: string; confirmed_orders: number }>;
}

export type { ProviderMenusEdit };
