// Typelizer digest abacc57d7ffd54dcb28ff1f1b2587564
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderCollectionOrder = {
  id: number;
  amount: number | null;
  menu_name: string;
  consumer_name: string;
  delivery_date: string | null;
  charged: number;
  subsidy: number;
}

export type { ProviderCollectionOrder };
