// Typelizer digest 61c69e85b43f04abd008c7b2d3b5e45b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderDashboardProvider} from '@/types'

type ProviderDashboardIndex = {
  today: unknown;
  today_orders_count: unknown;
  pending_orders_count: unknown;
  office_orders_count: unknown;
  home_orders_count: unknown;
  order_deadline: unknown;
  order_deadline_passed_today: unknown;
  month_orders_count: unknown;
  month_dishes_count: unknown;
  average_rating: unknown;
  provider: ProviderDashboardProvider;
}

export type { ProviderDashboardIndex };
