// Typelizer digest 2a74379b430a082b01f6fd4b9bd290ae
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {OrderStatus} from '@/types'

type ProviderOrder = {
  id: number;
  status: OrderStatus;
  amount: number | null;
  notes: string | null;
  price: number;
  time: string;
  consumer_name: string;
  menu_name: string;
  address: string | null;
}

export type { ProviderOrder };
