// Typelizer digest 2999a64f26d538933279df6cd7d37a55
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderOperationalSettingsProvider = {
  order_deadline: unknown;
}

export type { ProviderOperationalSettingsProvider };
