// Typelizer digest 4262581f6c23cfad9075d620e5208440
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {InvoiceStatus} from '@/types'

type ProviderInvoice = {
  id: number;
  status: InvoiceStatus;
  removable: boolean;
  total_amount: number;
  issued_on: string;
  file_name: string;
  file_size: string;
}

export type { ProviderInvoice };
