// Typelizer digest 8a8c960b9ee2e4eea57f122d08c7078e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderCollectionAccount = {
  id: number;
  owner_name: string;
  meals: number;
  amount: number;
  source: 'consumer' | 'company';
  status: 'pending' | 'submitted' | 'approved' | 'rejected';
  overdue: boolean;
  month: string;
  due_date: string;
  paid_on: string | null;
}

export type { ProviderCollectionAccount };
