// Typelizer digest a64f17ff79fb43c48a3298fa7ef04924
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderInvoice, ProviderCollectionOrder, ProviderCollectionPayment} from '@/types'

type ProviderCollectionAccount = {
  id: number;
  owner_name: string;
  meals: number;
  amount: number;
  source: 'consumer' | 'company';
  status: 'pending' | 'submitted' | 'approved' | 'rejected';
  can_approve_payment: boolean;
  overdue: boolean;
  debt_reminder: { eligible: boolean; remaining: number; next_available_at: string | null; blocked_reason: string | null };
  month: string;
  due_date: string;
  paid_on: string | null;
  payment_id: number | null;
  receipt_url: string | null;
  receipt_content_type: string | null;
  invoice: ProviderInvoice | null;
  orders: Array<ProviderCollectionOrder>;
  payments: Array<ProviderCollectionPayment>;
}

export type { ProviderCollectionAccount };
