// Typelizer digest a3c5f700902acddd3662af63a7e7ff52
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderMenusNew = {
  today: string;
  maximum_publish_date: string;
}

export type { ProviderMenusNew };
