// Typelizer digest 0c608eac8effb4e62d67a598b8297cd7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderOrderDetail = {
  id: unknown;
  status: unknown;
  amount: unknown;
  notes: unknown;
  delivery_method: unknown;
  price: unknown;
  date: unknown;
  time: unknown;
  consumer_name: unknown;
  consumer_company: unknown;
  menu_name: unknown;
  address: unknown;
  consumer_email: unknown;
  created_on: unknown;
  menu_description: unknown;
  menu_option_groups: unknown;
  selected_options: unknown;
  discounted_price: unknown;
  subsidy: unknown;
  schedule_amount: unknown;
  remaining_amount: unknown;
  rejection_reason: unknown;
  rejection_details: unknown;
}

export type { ProviderOrderDetail };
