// Typelizer digest 89aee0619851ba96462ac9670cd9207a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderOrder = {
  id: unknown;
  status: unknown;
  amount: unknown;
  notes: unknown;
  delivery_method: unknown;
  price: unknown;
  date: unknown;
  time: unknown;
  consumer_name: unknown;
  consumer_company: unknown;
  menu_name: unknown;
  address: unknown;
}

export type { ProviderOrder };
