// Typelizer digest 0eab6b18436c0d3e8b37278f856a8587
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOperationalSettingsProvider} from '@/types'

type ProviderOperationalSettingsShow = {
  provider: ProviderOperationalSettingsProvider;
  order_deadline_passed_today: unknown;
}

export type { ProviderOperationalSettingsShow };
