// Typelizer digest ea2fc4042867b13b63def1ff5f784fb5
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionAccount} from '@/types'

type ProviderCollectionGroup = {
  key: unknown;
  meals: unknown;
  awaiting_count: unknown;
  rejected_count: unknown;
  client_id: unknown;
  client_name: unknown;
  month: unknown;
  total: unknown;
  confirmed_total: unknown;
  employees_total: unknown;
  employees_status: unknown;
  company: ProviderCollectionAccount;
  employees: Array<ProviderCollectionAccount>;
}

export type { ProviderCollectionGroup };
