// Typelizer digest 8ba96abd3ea389cc0adbfc0d0f9b4694
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderCollectionOrder = {
  id: unknown;
  amount: unknown;
  menu_name: unknown;
  consumer_name: unknown;
  delivery_date: unknown;
  charged: unknown;
  subsidy: unknown;
}

export type { ProviderCollectionOrder };
