// Typelizer digest 9e342b604ca7f6793505c2d3e752972a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type ProviderPayment = {
  id: number;
  status: PaymentStatus;
  amount: number;
  date: string;
  employee_name: string;
  receipt_url: string | null;
}

export type { ProviderPayment };
