// Typelizer digest 61abae00dde3225e5b6f8f4d05019556
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderDashboardProvider = {
  order_deadline?: string;
}

export type { ProviderDashboardProvider };
