// Typelizer digest 933030244cae7aa7896541af295ace52
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Provider = {
  id: number;
  home_delivery: boolean;
  name: unknown;
}

export type { Provider };
