// Typelizer digest 6fa82b64f790449bc44b07454ea8b1e7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionAccount, ProviderCollectionOrder, ProviderCollectionPayment} from '@/types'

type ProviderCollectionsShow = {
  account: ProviderCollectionAccount;
  orders: Array<ProviderCollectionOrder>;
  payments: Array<ProviderCollectionPayment>;
}

export type { ProviderCollectionsShow };
