// Typelizer digest baf91c1c59ec041275ab53d6a01a8a75
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Menu} from '@/types'

type ProviderMenusEdit = {
  menu: Menu;
  saved_menu_id: unknown;
  schedule_date: unknown;
  today: unknown;
  maximum_publish_date: unknown;
  agenda: unknown;
  scheduled_days: unknown;
}

export type { ProviderMenusEdit };
