// Typelizer digest 0aaf9d75c0785e51964bd12d48010fad
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {PaymentStatus} from '@/types'

type ProviderCollectionPayment = {
  id: number;
  status: PaymentStatus;
  rejection_reason: string | null;
  date: string;
  receipt_url: string | null;
  receipt_filename: string | null;
  receipt_content_type: string | null;
}

export type { ProviderCollectionPayment };
