// Typelizer digest dd10da9be349241799409e398132e387
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderOrder} from '@/types'

type ProviderOrdersIndex = {
  today: string;
  upcoming_orders: Array<ProviderOrder>;
  past_orders: Array<ProviderOrder>;
}

export type { ProviderOrdersIndex };
