// Typelizer digest 7b6a9b8f102a04f4150462a384db3b54
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionGroup} from '@/types'

type ProviderCollectionsIndex = {
  sales: { total: number; meals: number };
  sales_detail: { month: string; clients: Array<{ id: number; name: string }>; days: Array<{ date: string; orders: Array<{ id: number; consumer_name: string; client_id: number; client_name: string; meals: number; amount: number }> }> };
  outstanding: { total: number; meals: number };
  clients: Array<{ id: number; name: string }>;
  pending: Array<ProviderCollectionGroup>;
  history: Array<ProviderCollectionGroup>;
}

export type { ProviderCollectionsIndex };
