// Typelizer digest c773e2a1302fb619dea92b5704b84b6c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Provider = {
  id: number;
  name: string;
}

export type { Provider };
