// Typelizer digest 628c00dff395cd6960cb875587d50eba
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderMenusNew = {
  today: unknown;
  maximum_publish_date: unknown;
}

export type { ProviderMenusNew };
