// Typelizer digest d51c8731cb8d446ec0a7dfb1f02efbde
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ProviderOperationalSettingsProvider = {
  order_deadline?: string;
}

export type { ProviderOperationalSettingsProvider };
