// Typelizer digest 6653b6f732a544c4d7fb37a04a13fc6a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderCollectionGroup} from '@/types'

type ProviderCollectionsIndex = {
  sales: unknown;
  sales_detail: unknown;
  outstanding: unknown;
  clients: unknown;
  pending: Array<ProviderCollectionGroup>;
  history: Array<ProviderCollectionGroup>;
}

export type { ProviderCollectionsIndex };
