// Typelizer digest b7750bd69c1acb7fa5e0dcc51d11e56d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {ProviderInvoice, ProviderCollectionOrder, ProviderCollectionPayment} from '@/types'

type ProviderCollectionAccount = {
  id: unknown;
  owner_name: unknown;
  meals: unknown;
  amount: unknown;
  source: unknown;
  status: unknown;
  can_approve_payment: unknown;
  overdue: unknown;
  debt_reminder: unknown;
  month: unknown;
  due_date: unknown;
  paid_on: unknown;
  payment_id: unknown;
  receipt_url: unknown;
  receipt_content_type: unknown;
  invoice: ProviderInvoice;
  orders: Array<ProviderCollectionOrder>;
  payments: Array<ProviderCollectionPayment>;
}

export type { ProviderCollectionAccount };
