// Typelizer digest 694affa26b33bf340c0889ff4113b3d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SavedMenu = {
  id: number;
  name: string | null;
  description: string | null;
  price: number | null;
  confirmed_orders: number;
  pending_orders: number;
  weekdays: Array<number>;
}

export type { SavedMenu };
