// Typelizer digest a249eb8539a3219d8b10741750124450
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Schedule = {
  id: number;
  menu_id: number;
  amount: number;
}

export type { Schedule };
