// Typelizer digest 7bfa50ff280c73c571c4005d920d0623
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Menu} from '@/types'

type Schedule = {
  id: number;
  menu_id: number;
  amount: number | null;
  available: boolean;
  saved_menu_id: number;
  menu: Menu;
}

export type { Schedule };
