// Typelizer digest 4573cb1af8cc6393063daec820dbe8d8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Menu} from '@/types'

type Schedule = {
  id: number;
  menu_id: number;
  amount: number;
  available: boolean;
  menu: Menu;
}

export type { Schedule };
