// Typelizer digest eec180b60327eafb2ef4a0d0c191b5bd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SessionsNew = {
  dev_login_enabled: boolean;
}

export type { SessionsNew };
