// Typelizer digest 330f397de07186e55deb640edd539d33
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SessionsNew = {
  dev_login_enabled: unknown;
}

export type { SessionsNew };
