// Typelizer digest 0327f35ccb05058c7a1d3892f6ffa0e2
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {SessionRole} from '@/types'

type Session = {
  id: number;
  user_agent: string | null;
  ip_address: string | null;
  created_at: string;
  role: SessionRole;
}

export type { Session };
