// Typelizer digest e766dad7397d40ea3301295c9e03bb9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Provider} from '@/types'

type SettingsProfilesShow = {
  provider: Provider;
}

export type { SettingsProfilesShow };
