// Typelizer digest 036fba4cc5270ef1334adbb651ef9647
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Provider} from '@/types'

type SettingsProfilesShow = {
  provider: Provider | null;
}

export type { SettingsProfilesShow };
