// Typelizer digest 2ce8a24a428bbe9d416499da705f3079
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth} from '@/types'

type SharedProps = {
  auth: Auth;
  locale: string;
  role: string;
}

export type { SharedProps };
