// Typelizer digest 0a6ce5a4d770e6a37da664d3dbccdb15
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth, Notification} from '@/types'

type SharedProps = {
  auth: Auth;
  notifications: Array<Notification>;
  locale: string;
}

export type { SharedProps };
