// Typelizer digest aded301a5ac1323bacfb9a57fa11971b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Auth, Notification} from '@/types'

type SharedProps = {
  auth: Auth;
  notifications: Array<Notification>;
  locale: unknown;
}

export type { SharedProps };
