// Typelizer digest 6217b39a0c3950d05423edc7d0e946f1
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SimplifiedOrder = {
  id: number;
  amount: number | null;
  price?: number;
  date?: string;
  menu_name?: string;
}

export type { SimplifiedOrder };
