// Typelizer digest 0db33ccdce6e1a38f68f8b618a6f1921
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SimplifiedOrder = {
  id: unknown;
  amount: unknown;
  price: unknown;
  date: unknown;
  menu_name: unknown;
}

export type { SimplifiedOrder };
