// Typelizer digest 72a003efebfefe6d2051e0d70d473068
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SimplifiedOrder = {
  id: number;
  amount: number | null;
  price: number | null;
  date?: string;
  menu_name?: string;
}

export type { SimplifiedOrder };
