// Typelizer digest 0b6061fd0adc8a77f5478d8d6a31249b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SpecialSubsidy = {
  id: unknown;
  name: unknown;
  subsidy_percentage: unknown;
  applies_to_all: unknown;
  consumer_ids: unknown;
  condition: unknown;
}

export type { SpecialSubsidy };
