// Typelizer digest 8b3fd630950aa224957fecbfb44ed4f3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type SpecialSubsidy = {
  id: number;
  name: string | null;
  subsidy_percentage: number;
  applies_to_all: boolean | null;
  consumer_ids: Array<number>;
  condition: { type: 'seniority' | 'birthday' | 'onboarding' | 'gift'; min_years?: number | null; limit?: number | null; validity_amount?: number | null; validity_unit?: 'days' | 'weeks' | 'months'; effective_from?: string | null } | null;
}

export type { SpecialSubsidy };
