// Typelizer digest 2f44356d89afae6fe16f21e2f34afb0c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
  avatar?: string;
  provider: boolean;
  consumer: boolean;
  admin: boolean;
}

export type { User };
