// Typelizer digest acbb041928c2cd2d8d97ed70b38367a4
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
  avatar: unknown;
  roles: Array<string>;
}

export type { User };
