// Typelizer digest 9b58e70920e80978143860c95fbb9fee
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type User = {
  id: number;
  name: string;
  email: string;
  verified: boolean;
  created_at: string;
  updated_at: string;
  avatar?: string;
  provider: boolean;
  consumer: boolean;
}

export type { User };
