// Typelizer digest cee693e652d130e66bcf9cee925dbe7b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /accounts */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/accounts', {}, options),
    method: 'get',
  }),

  /** GET /accounts/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/accounts/:id', params, options),
    method: 'get',
  }),
}
