// Typelizer digest f555f844bada0b3b8534dd10dee927fb
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /accounts */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/accounts', {}, options),
    method: 'get',
  }),
}
