// Typelizer digest 725e5a8ca6997105ebf37e5eb5f1b2d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard', {}, options),
    method: 'get',
  }),
}
