// Typelizer digest 7ea923d43668ba28662ade094c68241b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard', {}, options),
    method: 'get',
  }),

  /** GET /dashboard/confirmation */
  confirmed: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard/confirmation', {}, options),
    method: 'get',
  }),
}
