// Typelizer digest 16c863590fa10c914b27c92f73e0a59f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /dashboard */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard', {}, options),
    method: 'get',
  }),

  /** GET /dashboard/confirmation */
  confirmation: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/dashboard/confirmation', {}, options),
    method: 'get',
  }),
}
