// Typelizer digest a4f1855e615ac15080e3c3756581197c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /delivery_addresses */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/delivery_addresses', {}, options),
    method: 'post',
  }),
}
