// Typelizer digest 39f58f5be67c256dc4df05c5f3f56313
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /menus */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/menus', {}, options),
    method: 'get',
  }),

  /** GET /menus/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/menus/:id', params, options),
    method: 'get',
  }),
}
