// Typelizer digest 71fe607444bd8e3623603ae93ad4571b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /menus */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/menus', {}, options),
    method: 'get',
  }),
}
