// Typelizer digest 993d347a8bab09f5d71d03e68cbc2a18
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /orders */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'post',
  }),
}
