// Typelizer digest 2e64d886eb92caf267d7ec3ea6d8bf75
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** PATCH /orders/:id/cancel */
  cancel: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/orders/:id/cancel', params, options),
    method: 'patch',
  }),

  /** GET /orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'get',
  }),

  /** POST /orders */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'post',
  }),

  /** GET /orders/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/orders/:id', params, options),
    method: 'get',
  }),
}
