// Typelizer digest 6d3279ee1671290312fd494167b140b3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /orders */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'get',
  }),

  /** POST /orders */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/orders', {}, options),
    method: 'post',
  }),

  /** GET /orders/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/orders/:id', params, options),
    method: 'get',
  }),
}
