// Typelizer digest e301b5b47a535345f6eb3b3e1c2024d3
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /payments/:id/receipt */
  receipt: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/payments/:id/receipt', params, options),
    method: 'get',
  }),

  /** POST /payments */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/payments', {}, options),
    method: 'post',
  }),

  /** PATCH /payments/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/payments/:id', params, options),
    method: 'patch',
  }),

  /** DELETE /payments/:id */
  destroy: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'delete'> => ({
    url: buildUrl('/payments/:id', params, options),
    method: 'delete',
  }),
}
