// Typelizer digest 82bc8600e6a4ee54c477eb90ad2d44d6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /payments/:id/receipt */
  receipt: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/payments/:id/receipt', params, options),
    method: 'get',
  }),

  /** GET /payments */
  payments: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/payments', {}, options),
    method: 'get',
  }),

  /** POST /payments */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/payments', {}, options),
    method: 'post',
  }),

  /** PATCH /payments/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/payments/:id', params, options),
    method: 'patch',
  }),

  /** GET /payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/payments', {}, options),
    method: 'get',
  }),
}
