// Typelizer digest cd9c5d943f5840df26d5010a39b85fb7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /payments */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/payments', {}, options),
    method: 'get',
  }),
}
