// Typelizer digest afff52c4c70071ff26df77d26fbf3a58
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /profile */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/profile', {}, options),
    method: 'get',
  }),
}
